name: big_ear
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  carousel_slider: ^5.1.1
  webview_flutter: ^4.7.0 
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2
  url_launcher: ^6.3.2
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # 👈 Add it here

flutter:
  uses-material-design: true

  assets:
    - assets/images/  
    - assets/icons/  
    - assets/fonts/
    - assets/testing/
    - assets/images/image-4.jpg
    - assets/images/image-5.jpg
    - assets/images/construction.jpg
    

  fonts:
    - family: Ubuntu 
      fonts:
        - asset: assets/fonts/Ubuntu-R.ttf 
        - asset: assets/fonts/Ubuntu-B.ttf    


flutter_icons:  # 👈 Add this at the bottom
  android: true
  ios: true
  image_path: "assets/icons/app-icon.png"
